<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Checkout_fa fa-search</name>
   <tag></tag>
   <elementGuidId>b8c7a5aa-a65f-4d6b-b554-286c0facd7ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_form']/div/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e3e4ea0d-4e4d-4fed-8081-a846a9d50508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>a243367c-85e5-45b7-bcbc-71e5e04f17e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_form&quot;)/div[@class=&quot;btn-group search-bar&quot;]/div[@class=&quot;button-in-search&quot;]/i[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>48e7bb16-42c2-4b55-9f5b-26662cd6e385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_form']/div/div/i</value>
      <webElementGuid>bc1f0489-bcd0-49ca-83b0-5bb9ee91bc8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>f131b13c-7b45-40e7-946f-84e47bfa08ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
