<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>2f2b7676-576e-4abb-b447-8381ef119b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.col-md-2.col-sm-2.col-xs-6.align_center > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontainer']/div/div/div/div/ul/li/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e128e4a6-ecce-4e9b-a10b-5b8c9f6900db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sewriveting.ca/store/image/thumbnails/18/72/demo_product_23_jpg-100131-120x120.jpg</value>
      <webElementGuid>ad8ad43c-bd58-4240-b165-b9bf766312db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>9fc5b504-4119-4d4b-ac1f-62fa956d5288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>0ce66f79-94c5-4496-9498-90b9d3f02362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontainer&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12 col-xs-12 mt20&quot;]/div[1]/div[@class=&quot;contentpanel&quot;]/ul[@class=&quot;thumbnails row&quot;]/li[@class=&quot;col-md-2 col-sm-2 col-xs-6 align_center&quot;]/a[1]/img[1]</value>
      <webElementGuid>0d04bb5f-2409-431a-b678-f786bb36d744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/ul/li/a/img</value>
      <webElementGuid>7b28c31a-e606-4b8e-879e-c6fb7c373992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/img</value>
      <webElementGuid>826a09ef-b52e-40a0-93e9-061b8b175a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sewriveting.ca/store/image/thumbnails/18/72/demo_product_23_jpg-100131-120x120.jpg']</value>
      <webElementGuid>2d681e5f-bc02-46e9-8f50-1d3d4cde760e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
