<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort By_list</name>
   <tag></tag>
   <elementGuidId>e7028f75-488d-4a82-bc3b-1dbe24d8b129</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cbd8fd9-05e6-4a79-bbdc-6a53226a3ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>d401a295-b3f8-40fc-b960-6796e1c2e819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>d46a481b-d2bb-41fa-bfb0-e7af0d68b1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)</value>
      <webElementGuid>eb8b8ad6-3b00-41ba-9ea7-9a34d610f238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='list']</value>
      <webElementGuid>5b73efa1-f4fa-4f00-91b2-8a413a8b5adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div/div/button</value>
      <webElementGuid>38c73dfc-36ed-429c-a9e9-0370ddb38bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gift Ideas &amp; Sets'])[3]/following::button[1]</value>
      <webElementGuid>13e1b547-7360-41a8-b02c-d702ce3dc652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Night Care Crema Nera Obsidian Mineral Complex'])[1]/preceding::button[2]</value>
      <webElementGuid>f1c91fd1-3f5c-4565-a465-07dd3be0ef16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::button[2]</value>
      <webElementGuid>c41125f0-b749-4194-ad52-dd0b7f26258b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>f3a276c8-4a34-4662-b670-c5c90d59d8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'list']</value>
      <webElementGuid>204c8b90-4b7e-4f49-9767-5e4c3cd7259d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
