<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apparel  accessories</name>
   <tag></tag>
   <elementGuidId>de2fb784-9b83-433a-af48-76ab4c194731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='category_68']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#category_68</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>763a72d9-d7b5-4379-9297-662e5d9712c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_68</value>
      <webElementGuid>64586406-e6a5-4134-8441-05637bcf2944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apparel &amp; accessories</value>
      <webElementGuid>3af97ce9-f76c-4c35-8d35-6d9d27419f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_68&quot;)</value>
      <webElementGuid>757187bf-5f58-4873-b3ad-f701b67f8b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='category_68']</value>
      <webElementGuid>06b711a4-a9bf-4769-b101-84ff067eb8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='search-category']/li[4]/a</value>
      <webElementGuid>8870a1b5-eb2a-45f8-8532-2926a85dcc18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Apparel &amp; accessories')]</value>
      <webElementGuid>b725650e-5874-4567-9f98-44fb91051da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[2]/following::a[1]</value>
      <webElementGuid>b01e28fd-21f8-4427-a054-c7ad87c259a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Categories'])[1]/following::a[2]</value>
      <webElementGuid>1002ded2-394d-4869-90d8-677790b35d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skincare'])[1]/preceding::a[1]</value>
      <webElementGuid>417a7600-30f1-4bba-8ff8-460aac328b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fragrance'])[1]/preceding::a[2]</value>
      <webElementGuid>ff14c207-f9b6-4ded-a5d0-77dc84eccf61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apparel &amp; accessories']/parent::*</value>
      <webElementGuid>a92efa34-983f-4d3e-960b-3a8fc71b75a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/ul/li[4]/a</value>
      <webElementGuid>f1a661f4-a9c5-47f5-a239-642bc071ecde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'category_68' and (text() = 'Apparel &amp; accessories' or . = 'Apparel &amp; accessories')]</value>
      <webElementGuid>e790a342-3083-4e3b-afdd-d65758cc2da8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
