<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Order ID_order_id</name>
   <tag></tag>
   <elementGuidId>d19530a5-3e7b-482e-b20d-0b3135b9b3a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CheckOrderFrm_order_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CheckOrderFrm_order_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a02c3d15-c8ad-4cf1-9cf5-5e4538340648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6eddea1-b3cb-4608-9d06-698861fac97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_id</value>
      <webElementGuid>c441963e-4a56-4e32-ac6e-b9594d5366d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CheckOrderFrm_order_id</value>
      <webElementGuid>1ee42d0e-f0d1-4dd7-b056-563a5fe5b5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>38404878-4dee-44f4-9e28-26964b822824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CheckOrderFrm_order_id&quot;)</value>
      <webElementGuid>e1fc79b1-394e-42fe-9cca-34d8a0145483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CheckOrderFrm_order_id']</value>
      <webElementGuid>e8d2668a-9797-4d66-9964-828d9ac5be52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='CheckOrderFrm']/div/fieldset/div/div/input</value>
      <webElementGuid>ca339fb4-6a32-4832-8465-34e2b6ed639f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>b9500b32-8d60-4f3b-9a45-62a46c1e80f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'order_id' and @id = 'CheckOrderFrm_order_id']</value>
      <webElementGuid>9d00aa44-8ef9-4915-b61b-163793078ea6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
