<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Sort By_fa fa-th</name>
   <tag></tag>
   <elementGuidId>4533d083-290a-4108-9f42-160c44ee2c48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-th</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='grid']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aabb2643-17d4-40ff-9452-9646afc744d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-th</value>
      <webElementGuid>75f9073f-ada5-44e8-8d1f-d52ea612d332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)/i[@class=&quot;fa fa-th&quot;]</value>
      <webElementGuid>9b151069-a937-4671-ad75-0508dc42d79e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='grid']/i</value>
      <webElementGuid>c4ffa626-c7bc-481d-b882-789516948717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>37a9b360-6722-46ce-b170-fbf50b624f42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
