<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bestsellers</name>
   <tag></tag>
   <elementGuidId>a38ddba6-eefa-439b-a82f-815d54651524</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_frame_bestsellers_2641']/h1/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#block_frame_bestsellers_2641 > h1.heading1 > span.maintext</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcadd4d8-3663-4490-b52e-cc86b5b981d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>maintext</value>
      <webElementGuid>533d2a16-8b1f-45ae-8a1f-f8d35a33c24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestsellers</value>
      <webElementGuid>4245e86f-51d5-4adb-b922-b5b76cb29e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_frame_bestsellers_2641&quot;)/h1[@class=&quot;heading1&quot;]/span[@class=&quot;maintext&quot;]</value>
      <webElementGuid>72a6229c-5a36-4f54-91c5-35a1c4b7a251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_frame_bestsellers_2641']/h1/span</value>
      <webElementGuid>776c5c80-95a8-4c7d-8e4c-9a53fddcc9ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$25.29'])[1]/following::span[1]</value>
      <webElementGuid>b911c6fa-32c1-44be-ba32-4ca1140af28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$21.25'])[1]/following::span[1]</value>
      <webElementGuid>c40a106f-b183-4617-874a-64253548a5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See Best Selling Products'])[1]/preceding::span[1]</value>
      <webElementGuid>23bc2baa-a45d-4945-971f-d5eff98cae13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BeneFit Girl Meets Pearl'])[1]/preceding::span[2]</value>
      <webElementGuid>37eaa0c7-a7ae-4886-ad95-a553a7355c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bestsellers']/parent::*</value>
      <webElementGuid>046cd3ec-392b-4394-8daa-7810053389b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/h1/span</value>
      <webElementGuid>ae629bd9-2ee3-49a5-87e2-5309c8ee44e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bestsellers' or . = 'Bestsellers')]</value>
      <webElementGuid>149b8b97-fb5a-4c7f-86f3-bfa96649a121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
