<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Total</name>
   <tag></tag>
   <elementGuidId>0bddf864-321b-4132-be27-fa5d621cdb05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart_details']/ul/li[7]/h4/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.list-group-item-heading > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Total:&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>945fe6f4-4d2f-4935-9665-fbec1a4a1452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total:</value>
      <webElementGuid>79a42f78-c47e-4ac7-94c7-4485e9f0de78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart_details&quot;)/ul[@class=&quot;list-group&quot;]/li[@class=&quot;list-group-item&quot;]/h4[@class=&quot;list-group-item-heading&quot;]/b[1]</value>
      <webElementGuid>1e14b9bb-812f-4203-8eff-c1f35722b79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart_details']/ul/li[7]/h4/b</value>
      <webElementGuid>8e6695ba-593b-45b9-8df6-c6153bc45d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$224.86'])[1]/following::b[1]</value>
      <webElementGuid>b6c1d043-0de4-4732-b24d-289a1846228f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HST (13%):'])[1]/following::b[2]</value>
      <webElementGuid>f4a49521-7fc1-4931-b438-56598f032e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the delivery options'])[1]/preceding::b[1]</value>
      <webElementGuid>94599afc-9163-4560-93d8-a342c30ac026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Address:'])[1]/preceding::b[1]</value>
      <webElementGuid>7a80a8f2-600d-4ba6-b5f1-0b5b3888c058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Total:']/parent::*</value>
      <webElementGuid>731491d0-8333-484b-a5a1-cdc0fdb12b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4/b</value>
      <webElementGuid>9fb8c426-e993-49f2-ab45-e6dd0c5644d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Total:' or . = 'Total:')]</value>
      <webElementGuid>4335aada-be8b-4e8e-90b2-520157c8709c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
