<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nathan Gamble PLATOTech 179 Prom. du Po_cc030e</name>
   <tag></tag>
   <elementGuidId>ca56eded-4c33-4dfe-a5dc-663023e14ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='PayFrm']/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shipping_address_details</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Nathan Gamble PLATOTech 179 Prom. du Portage Gatineau J8X 2K5 Québec Canada&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5fcc553-b9d1-41a8-8a09-bac4a920fa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shipping_address_details</value>
      <webElementGuid>8f6187a1-070e-4182-9878-25a54c81b35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nathan Gamble PLATOTech 179 Prom. du Portage Gatineau  J8X 2K5 Québec Canada</value>
      <webElementGuid>43281f53-b5ae-4944-8557-68b5bb6666de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PayFrm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;shipping_address_details&quot;]</value>
      <webElementGuid>3a8cb5ef-ce23-4036-8f28-6ea28666c58e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayFrm']/div[2]/div/div[3]</value>
      <webElementGuid>c7954016-6ae4-432a-a15d-d3b122e82566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Address:'])[1]/following::div[3]</value>
      <webElementGuid>eb5191d2-f38c-4224-ad20-7c403d96044c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the delivery options'])[1]/following::div[6]</value>
      <webElementGuid>5e74eddd-5f01-4864-8b32-9709ed1e4f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pickup'])[1]/preceding::div[2]</value>
      <webElementGuid>6d9f7dc6-6348-40d7-9ba3-597d92bcb5d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pickup From Store'])[1]/preceding::div[3]</value>
      <webElementGuid>640df01f-bfed-4ea6-aabe-687c198aff44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nathan Gamble']/parent::*</value>
      <webElementGuid>3ceb9b0b-e915-4580-9c5a-788d88c985ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div[3]</value>
      <webElementGuid>be5224b1-dd43-4e74-a7c7-9711151f3a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nathan Gamble PLATOTech 179 Prom. du Portage Gatineau  J8X 2K5 Québec Canada' or . = 'Nathan Gamble PLATOTech 179 Prom. du Portage Gatineau  J8X 2K5 Québec Canada')]</value>
      <webElementGuid>4ed428b5-18e6-4225-8b55-f5d94b982229</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
