<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Order is completed</name>
   <tag></tag>
   <elementGuidId>9ab49938-4e18-4b1f-99e0-44dfaa0bb9a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fast_checkout_success']/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.text-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Order is completed!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>aa1a5636-4d0f-4e90-ac6c-ac0f019c33a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-success</value>
      <webElementGuid>859a323d-2aa6-4648-9eda-214ff10cd3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order is completed!</value>
      <webElementGuid>085768e3-dd93-4817-bb4c-9b0642e9fb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast_checkout_success&quot;)/div[@class=&quot;pay-form&quot;]/div[@class=&quot;text-center order-success&quot;]/div[@class=&quot;order-success&quot;]/h3[@class=&quot;text-success&quot;]</value>
      <webElementGuid>e941d47d-1508-403a-9bb9-d03da6e4066b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast_checkout_success']/div/div/div/h3</value>
      <webElementGuid>f947c855-b1cd-4645-af7e-0bbf046b9e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbanteCart'])[1]/preceding::h3[1]</value>
      <webElementGuid>acb06019-f287-4f47-908d-28da803c4b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Order is completed!']/parent::*</value>
      <webElementGuid>63769974-fff3-4bb2-ba5b-f94ac5f4562a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>e154e054-49d3-43dc-8f16-2328296f302d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Order is completed!' or . = 'Order is completed!')]</value>
      <webElementGuid>87949628-6b08-4946-b79c-36b985cb7c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
