<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pickup From Store</name>
   <tag></tag>
   <elementGuidId>0a1a39be-0a4e-4a9c-8cf9-1e8b18a9bd42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='default_store_pickup.default_store_pickup_title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Pickup From Store&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>eb5034cf-f64f-4917-a328-62add03464f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>default_store_pickup.default_store_pickup_title</value>
      <webElementGuid>cf3f7bb7-2712-4912-906a-1c19f07cafbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>default_store_pickupdefault_store_pickupdefault_store_pickup.default_store_pickup</value>
      <webElementGuid>918f9395-22e7-4982-896a-9b6d2949cf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pickup From Store</value>
      <webElementGuid>7aeeb33f-44e9-4b7d-893d-e728d16a0a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                                                Pickup From Store                                                    </value>
      <webElementGuid>09a62ea5-2f65-438f-943e-73184c907904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;default_store_pickup.default_store_pickup_title&quot;)</value>
      <webElementGuid>db58fa53-7926-44f7-b6a6-b76665e701cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='default_store_pickup.default_store_pickup_title']</value>
      <webElementGuid>b842d73c-7606-40a9-8ad6-e25302c85667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='PayFrm']/div[2]/div[2]/div/table/tbody/tr[2]/td[2]/label</value>
      <webElementGuid>7feba242-e4f7-4a4e-931c-d542855039cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pickup'])[1]/following::label[2]</value>
      <webElementGuid>59a683e2-6c12-4702-9c9f-6ecb46fec826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free'])[1]/preceding::label[1]</value>
      <webElementGuid>1805c723-b91c-49b2-a96d-9ebc7fad5a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Local Delivery'])[1]/preceding::label[2]</value>
      <webElementGuid>f5985d91-c3e8-40b3-80fd-8c598e58cb44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pickup From Store']/parent::*</value>
      <webElementGuid>88f64ef6-429d-41c6-9635-20476ffba420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/label</value>
      <webElementGuid>ddf72f84-76f8-4868-a24e-890b6ad605eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'default_store_pickup.default_store_pickup_title' and @title = 'Pickup From Store' and (text() = '
                                                                                                                Pickup From Store                                                    ' or . = '
                                                                                                                Pickup From Store                                                    ')]</value>
      <webElementGuid>29df8d71-e7fc-4d6f-8c2a-988b2c14ee21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
