<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BeneFit Remove from Cart Button</name>
   <tag></tag>
   <elementGuidId>a80c4bd8-3d7c-40b3-a553-4bab93146898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cart']/div/table/tbody/tr[2]/td[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-sm.btn-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5a17789-353b-4d0f-898b-ed5fdf3dd3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sewriveting.ca/store/index.php?rt=checkout/cart&amp;remove=51</value>
      <webElementGuid>07fb7d75-3689-4e42-a9aa-b65819050ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-default</value>
      <webElementGuid>62c25596-c1b0-4ee3-99b3-15d6770ed655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart&quot;)/div[@class=&quot;container-fluid cart-info product-list&quot;]/table[@class=&quot;table table-striped table-bordered&quot;]/tbody[1]/tr[2]/td[@class=&quot;align_center&quot;]/a[@class=&quot;btn btn-sm btn-default&quot;]</value>
      <webElementGuid>64df0c11-dda0-4fb5-a93e-4993f7202d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cart']/div/table/tbody/tr[2]/td[7]/a</value>
      <webElementGuid>1450015c-8367-4f63-a3d6-dbedd3051cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$13.93'])[4]/following::a[1]</value>
      <webElementGuid>c9b792f6-6f29-441a-afe3-0a268a638cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$13.93'])[3]/following::a[1]</value>
      <webElementGuid>90746e08-cf1c-4752-be23-6dac198bad7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Coupon Code'])[1]/preceding::a[2]</value>
      <webElementGuid>1930083e-a630-44be-b1d2-49e7561667f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sewriveting.ca/store/index.php?rt=checkout/cart&amp;remove=51')]</value>
      <webElementGuid>ac4b7e17-d8d8-47da-b8b4-3bde48afef6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a</value>
      <webElementGuid>718bbd0e-c091-4e5a-b910-a3fcb42eac63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sewriveting.ca/store/index.php?rt=checkout/cart&amp;remove=51']</value>
      <webElementGuid>77154fe1-8533-4b0b-839e-6ed450da31c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
