<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Shipments</name>
   <tag></tag>
   <elementGuidId>101256f2-f933-4b1f-87a5-9a1b5d0ab7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='estimate']/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.shippings-offered.form-group > label.control-label.col-sm-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Shipments&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ad82a9b7-9004-46f5-aa16-134a78bb7da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label col-sm-4</value>
      <webElementGuid>2cb49cc7-fdb1-4b12-8ec2-1e10d4faee1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipments</value>
      <webElementGuid>108936f0-c5e5-45d3-af27-67cb9ffc8a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;estimate&quot;)/div[@class=&quot;shippings-offered form-group&quot;]/label[@class=&quot;control-label col-sm-4&quot;]</value>
      <webElementGuid>ae26b93d-ddee-4000-8440-ed4818ced5d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='estimate']/div[3]/label</value>
      <webElementGuid>8d57eca3-7c4f-48d3-b3a6-72018aca8002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP/Post Code'])[1]/following::label[1]</value>
      <webElementGuid>43e59ac0-8d67-4a9d-80f1-ec3e11dc727f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-Total:'])[2]/preceding::label[1]</value>
      <webElementGuid>4353fda8-b619-4181-93b7-2d218a1ea755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$66.33'])[2]/preceding::label[1]</value>
      <webElementGuid>a7184b92-c5af-48d4-be8e-d1a281d301d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipments']/parent::*</value>
      <webElementGuid>bd379717-63b6-4558-b37c-13ee632c4dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label</value>
      <webElementGuid>f30c9422-a9c1-4e17-99b8-02c7065f87aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Shipments' or . = 'Shipments')]</value>
      <webElementGuid>cb82e3ca-3389-4593-984a-8a209849b35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
