<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hands  Nails</name>
   <tag></tag>
   <elementGuidId>14b8a90f-0c57-44ef-8a0f-0c322e1a2167</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.subcategories > ul > li:nth-of-type(4) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='categorymenu']/nav/ul/li[3]/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9804d98-be80-42d9-b626-b620952fefbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sewriveting.ca/store/index.php?rt=product/category&amp;path=43_48</value>
      <webElementGuid>b9d2710d-031e-4398-9591-45d727550a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Hands &amp; Nails</value>
      <webElementGuid>cc397cb2-6580-4fed-b15c-d24e5d116ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;categorymenu&quot;)/nav[@class=&quot;subnav&quot;]/ul[@class=&quot;nav-pills categorymenu&quot;]/li[3]/div[@class=&quot;subcategories&quot;]/ul[1]/li[4]/a[1]</value>
      <webElementGuid>80054096-3cb2-4a6f-b9ac-1cfea74de191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='categorymenu']/nav/ul/li[3]/div/ul/li[4]/a</value>
      <webElementGuid>1de3ae2c-1573-4929-8485-6e0770a904ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hands &amp; Nails')]</value>
      <webElementGuid>0abad584-e86f-4caf-aa15-a284d3c2c51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sewriveting.ca/store/index.php?rt=product/category&amp;path=43_48')]</value>
      <webElementGuid>f45382e9-2d8e-4e81-8e20-70653bd84380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/ul/li[4]/a</value>
      <webElementGuid>b42bb992-c6c8-464a-9623-6d2e1583e5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sewriveting.ca/store/index.php?rt=product/category&amp;path=43_48' and (text() = '    Hands &amp; Nails' or . = '    Hands &amp; Nails')]</value>
      <webElementGuid>34fd35ef-d7c7-4de0-b7fe-f906c5a26ca8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
