<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Back to top</name>
   <tag></tag>
   <elementGuidId>e66d8cf4-613e-4a9b-9fce-aaf9a1419230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gotop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='gotop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0143f61c-812b-4185-94d6-cbfcc7065ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gotop</value>
      <webElementGuid>ca65bfae-0349-4ef9-931f-2fb0d1ea416e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>7577901c-87f9-4f5e-834d-0c22040abc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Back to top</value>
      <webElementGuid>df2b23c3-e149-4b29-b926-bc345fa008ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gotop&quot;)</value>
      <webElementGuid>ad274598-0b15-43fe-8ac5-044808c284e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='gotop']</value>
      <webElementGuid>d8248308-fee2-4d7d-87d7-35932f3826de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/footer/a</value>
      <webElementGuid>0c031464-fce5-4cfe-95c4-dd0f310192bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Back to top')]</value>
      <webElementGuid>f521cef7-9bab-4cdf-9559-969cd3173d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AbanteCart'])[1]/following::a[1]</value>
      <webElementGuid>c1c94b70-ffe0-48b8-bdb9-07c7c9b17612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Back to top']/parent::*</value>
      <webElementGuid>068b76f0-ce85-4c6c-adb5-e9f3fda9ce89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[26]</value>
      <webElementGuid>155dced7-87c1-45b7-b8c2-3b097912aaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/a</value>
      <webElementGuid>bbf61952-9347-4c9e-babe-934847da91c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'gotop' and @href = '#' and (text() = 'Back to top' or . = 'Back to top')]</value>
      <webElementGuid>8fe9fd80-ab25-41c7-943b-3ab51a0a0f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
