<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort By_list</name>
   <tag></tag>
   <elementGuidId>9ae1b4b1-6a77-4030-be85-7ae71b03f91e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='list']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>22b5ae66-f2b8-4a10-807e-5f40a9739223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn</value>
      <webElementGuid>93a7640a-ad66-4234-a921-22888ab973a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>dd7318e2-69bd-4770-831b-f760cb299dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)</value>
      <webElementGuid>9096426f-4534-46d3-a70b-e0a717ee5e0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='list']</value>
      <webElementGuid>a0bc0cdf-a84e-4b06-80e3-1aebbf3310d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div[2]/div/button</value>
      <webElementGuid>e42f7518-4b54-49fe-ad46-326072685382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Face'])[3]/following::button[1]</value>
      <webElementGuid>3cdf8743-c377-453f-ba36-d0338fd53048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Moisture Facial Cream'])[1]/preceding::button[2]</value>
      <webElementGuid>49b9637a-3e61-47d6-acb7-4c146435f952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::button[2]</value>
      <webElementGuid>8abb6d53-23de-4999-9f8a-33163043ece8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>6ad4f88b-884e-4e28-82ef-08facf4cf5e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'list']</value>
      <webElementGuid>96aa98e6-8892-4cb1-bf80-fea66dd97427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
