<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sort By_grid</name>
   <tag></tag>
   <elementGuidId>b3869635-41f4-4bcb-ba7e-f6938814633e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#grid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='grid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fa83e34c-a753-40fb-a9e3-45af2c1ddc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-orange</value>
      <webElementGuid>bed1ec60-9358-402d-a478-a2b271095417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>77c685a9-5139-42dd-84ca-88d5c7ccf5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid&quot;)</value>
      <webElementGuid>fbe547c9-00c8-4c8c-aa1c-906801b94836</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='grid']</value>
      <webElementGuid>27ffd0f4-6d24-43b9-99b5-5cb5156f8ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div[2]/div/button[2]</value>
      <webElementGuid>6978fe41-5d26-40b5-ae71-e1723500766c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Face'])[3]/following::button[2]</value>
      <webElementGuid>88eff2ac-067a-4906-9fc1-ff065569f87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Moisture Facial Cream'])[1]/preceding::button[1]</value>
      <webElementGuid>1a7e7459-511f-4526-a80f-819844b9dabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::button[1]</value>
      <webElementGuid>572e5b7c-9d66-4a86-8753-c0ab2053126e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>f1291799-534b-4d07-93c0-ffa6e76bee81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'grid']</value>
      <webElementGuid>4177e01d-319a-4c1e-8f48-83ead8a250c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
