<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1020304050</name>
   <tag></tag>
   <elementGuidId>505df53f-203d-4151-af22-dd351b99da7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#limit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='limit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>66b6a8c5-ca99-4a7e-a011-ce81d37237d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>1a26a8ae-23e8-4a1f-85d8-b4979ea806b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>af615106-1330-46d4-b518-381a8cac77b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-mini</value>
      <webElementGuid>bda6c05e-b833-4f7b-97a0-65b353cda9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>location='https://sewriveting.ca/store/index.php?rt=product/special&amp;sort=date_modified-DESC&amp;page=1&amp;limit='+this.value;</value>
      <webElementGuid>184a168a-d07a-4214-a256-cfa812c8d7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			10
			20
			30
			40
			50
	</value>
      <webElementGuid>c0bf2eea-b990-4154-a31c-eeacd8ec4a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;limit&quot;)</value>
      <webElementGuid>58c9d6ad-e5b4-449c-9960-b08be1e07186</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='limit']</value>
      <webElementGuid>57f573d4-0d43-4709-b583-c24fa2a0f990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontainer']/div/div/div/div/div[4]/form/select</value>
      <webElementGuid>c587bdbd-5403-4832-939b-e9639e32a239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$21.25'])[4]/following::select[1]</value>
      <webElementGuid>c6992a81-f003-489a-b68a-e14e35222b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::select[1]</value>
      <webElementGuid>4c61b582-d23e-4834-9f63-85e90852901c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/form/select</value>
      <webElementGuid>31cea861-1115-495b-8feb-363cfad4f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'limit' and @id = 'limit' and (text() = '
			10
			20
			30
			40
			50
	' or . = '
			10
			20
			30
			40
			50
	')]</value>
      <webElementGuid>57dca845-1b70-4ee5-8ca3-433d74b4019d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
