<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>02812096-d166-4afc-ae90-7c2d67d473c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product_details']/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.easyzoom-flyout > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>13a4d62b-800d-45ac-817e-2e543389522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//sewriveting.ca/store/image/thumbnails/18/79/t_shirt_4_jpg-100248-500x500.jpg</value>
      <webElementGuid>2eac0741-578e-4527-b68d-ee14c2414ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product_details&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 text-center&quot;]/div[@class=&quot;hidden-xs hidden-sm mainimage bigimage easyzoom easyzoom--overlay easyzoom--with-thumbnails is-ready&quot;]/div[@class=&quot;easyzoom-flyout&quot;]/img[1]</value>
      <webElementGuid>ca357903-33ab-439c-8270-23dd22d1d261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product_details']/div/div/div/div/img</value>
      <webElementGuid>4e41d701-c2a9-42f7-b1c6-75b4ce749b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>040e65d3-da5d-47c6-85c0-ce5b71941245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//sewriveting.ca/store/image/thumbnails/18/79/t_shirt_4_jpg-100248-500x500.jpg']</value>
      <webElementGuid>573f7824-52ac-4ef6-95b7-b987977ab700</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
